name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - drake

jobs:
  # Will be replaced by part of upstream's CI.
  placeholder:
    name: placeholder
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
